language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng test --watch=false --browsers=ChromeHeadless
- ng build --prod
